from django.contrib import admin
from django.urls import path, include
from learning_management_system import settings
from learning_management_app import views, SystemViews, StaffView, StudentView
from django.conf.urls.static import static

from learning_management_app.EditViewClass import EditResultViewClass

urlpatterns = [

    #Views & Admin URL Path
    path('login', views.showLoginPage, name='show_login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.showMainPage, name='show_main_page'),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user, name='logout_user'),
    path('doLogin', views.doLogin, name='do_login'),

    #System Views URL Path
    path('admin_home', SystemViews.admin_home, name='admin_home'),
    path('add_staff', SystemViews.add_staff, name='add_staff'),
    path('add_staff_save', SystemViews.add_staff_save, name='add_staff_save'),
    path('add_course', SystemViews.add_course, name='add_course'),
    path('add_course_save', SystemViews.add_course_save, name='add_course_save'),
    path('add_student', SystemViews.add_student, name='add_student'),
    path('check_email_exist', SystemViews.check_email_exist, name='check_email_exist'),
    path('check_username_exist', SystemViews.check_username_exist, name='check_username_exist'),
    path('add_student_save', SystemViews.add_student_save, name='add_student_save'),
    path('add_subject', SystemViews.add_subject, name='add_subject'),
    path('add_subject_save', SystemViews.add_subject_save, name='add_subject_save'),
    path('add_course_session_save', SystemViews.add_course_session_save, name='add_course_session_save'),
    path('manage_staff', SystemViews.manage_staff, name='manage_staff'),
    path('manage_student', SystemViews.manage_student, name='manage_student'),
    path('manage_course', SystemViews.manage_course, name='manage_course'),
    path('manage_subject', SystemViews.manage_subject, name='manage_subject'),
    path('manage_course_sessions', SystemViews.manage_course_sessions, name='manage_course_sessions'),
    path('edit_staff/<int:staff_id>/', SystemViews.edit_staff, name='edit_staff'),
    path('edit_staff_save', SystemViews.edit_staff_save, name='edit_staff_save'),
    path('edit_student/<str:student_id>/', SystemViews.edit_student, name="edit_student"),
    path('edit_student_save', SystemViews.edit_student_save, name="edit_student_save"),
    path('edit_subject/<str:subject_id>/', SystemViews.edit_subject, name="edit_subject"),
    path('edit_subject_save', SystemViews.edit_subject_save, name="edit_subject_save"),
    path('edit_course/<str:course_id>/', SystemViews.edit_course, name="edit_course"),
    path('edit_course_save', SystemViews.edit_course_save, name="edit_course_save"),
    path('staff_feedback_data', SystemViews.staff_feedback_data, name="staff_feedback_data"),
    path('student_feedback_data', SystemViews.student_feedback_data, name="student_feedback_data"),
    path('save_student_feedback_reply', SystemViews.save_student_feedback_reply, name="save_student_feedback_reply"),
    path('save_staff_feedback_reply', SystemViews.save_staff_feedback_reply, name="save_staff_feedback_reply"),
    path('staff_leave_view', SystemViews.staff_leave_view, name="staff_leave_view"),
    path('staff_approve_leave/<str:leave_id>', SystemViews.staff_approve_leave, name="staff_approve_leave"),
    path('staff_disapprove_leave/<str:leave_id>', SystemViews.staff_disapprove_leave, name="staff_disapprove_leave"),
    path('student_leave_view', SystemViews.student_leave_view, name="student_leave_view"),
    path('student_approve_leave/<str:leave_id>', SystemViews.student_approve_leave, name="student_approve_leave"),
    path('student_disapprove_leave/<str:leave_id>', SystemViews.student_disapprove_leave, name="student_disapprove_leave"),
    path('view_attendance_report', SystemViews.view_attendance_report, name="view_attendance_report"),
    path('admin_get_attendance_dates', SystemViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_student', SystemViews.admin_get_attendance_student, name="admin_get_attendance_student"),
    path('admin_update_attendance_data', SystemViews.admin_update_attendance_data, name="admin_update_attendance_data"),
    path('admin_profile', SystemViews.admin_profile, name="admin_profile"),
    path('edit_admin_profile', SystemViews.edit_admin_profile, name="edit_admin_profile"),
    path('admin_send_notification_staff', SystemViews.admin_send_notification_staff,name="admin_send_notification_staff"),
    path('admin_send_notification_student', SystemViews.admin_send_notification_student,name="admin_send_notification_student"),
    path('send_student_notification', SystemViews.send_student_notification,name="send_student_notification"),
    path('send_staff_notification', SystemViews.send_staff_notification,name="send_staff_notification"),

    #Staff Views URL Path
    path('staff_home', StaffView.staff_home, name="staff_home"),
    path('staff_take_attendance', StaffView.staff_take_attendance, name="staff_take_attendance"),
    path('get_students', StaffView.get_students, name="get_students"),
    path('save_attendance_data', StaffView.save_attendance_data, name="save_attendance_data"),
    path('staff_update_attendance', StaffView.staff_update_attendance, name="staff_update_attendance"),
    path('get_attendance_dates', StaffView.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student', StaffView.get_attendance_student, name="get_attendance_student"),
    path('update_attendance_data', StaffView.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave', StaffView.staff_apply_leave, name="staff_apply_leave"),
    path('staff_feedback', StaffView.staff_feedback, name="staff_feedback"),
    path('save_staff_feedback', StaffView.save_staff_feedback, name="save_staff_feedback"),
    path('save_staff_apply_leave', StaffView.save_staff_apply_leave, name="save_staff_apply_leave"),
    path('staff_profile', StaffView.staff_profile, name="staff_profile"),
    path('edit_staff_profile', StaffView.edit_staff_profile, name="edit_staff_profile"),
    path('staff_fcmtoken_save', StaffView.staff_fcmtoken_save, name="staff_fcmtoken_save"),
    path('staff_all_notification', StaffView.staff_all_notification, name="staff_all_notification"),
    path('staff_add_result', StaffView.staff_add_result, name="staff_add_result"),
    path('save_student_result', StaffView.save_student_result, name="save_student_result"),
    path('edit_student_result', EditResultViewClass.as_view(), name="edit_student_result"),
    path('fetch_result_student', StaffView.fetch_result_student, name="fetch_result_student"),
    #path('start_live_classroom',StaffView.start_live_classroom, name="start_live_classroom"),
    #path('start_live_classroom_process',StaffView.start_live_classroom_process, name="start_live_classroom_process"),

    #Student Views URL Path
    path('student_home', StudentView.student_home, name="student_home"),
    path('student_view_attendance', StudentView.student_view_attendance, name="student_view_attendance"),
    path('student_attendance_data', StudentView.student_attendance_data, name="student_attendance_data"),
    path('student_apply_leave', StudentView.student_apply_leave, name="student_apply_leave"),
    path('student_feedback', StudentView.student_feedback, name="student_feedback"),
    path('save_student_feedback', StudentView.save_student_feedback, name="save_student_feedback"),
    path('save_student_apply_leave', StudentView.save_student_apply_leave, name="save_student_apply_leave"),
    path('student_profile', StudentView.student_profile, name="student_profile"),
    path('edit_student_profile', StudentView.edit_student_profile, name="edit_student_profile"),
    path('student_fcmtoken_save', StudentView.student_fcmtoken_save, name="student_fcmtoken_save"),
    path('firebase-messaging-sw.js', views.showFirebaseJS, name="show_firebase_js"),
    path('student_all_notification', StudentView.student_all_notification,name="student_all_notification"),
    path('student_view_result', StudentView.student_view_result, name="student_view_result"),
    #path('join_class_room/<int:subject_id>/<int:session_year_id>', StudentViews.join_class_room,name="join_class_room"),
    #path('node_modules/canvas-designer/widget.html', StaffViews.returnHtmlWidget,name="returnHtmlWidget"),
    #path('testurl/', views.Testurl)

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
